FROM golang:1.25.1-alpine3.22

WORKDIR /backend

RUN apk add --no-cache make gcc musl-dev

RUN go install github.com/air-verse/air@latest
COPY .air.toml .

COPY go.mod go.sum ./

ENV APP_ENV=development

