// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const albumCreate = `-- name: AlbumCreate :one
INSERT INTO albums (spotify_id, name, track_amount, popularity, cover_id, cover_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type AlbumCreateParams struct {
	SpotifyID   string
	Name        pgtype.Text
	TrackAmount pgtype.Int4
	Popularity  pgtype.Int4
	CoverID     pgtype.Text
	CoverUrl    pgtype.Text
}

func (q *Queries) AlbumCreate(ctx context.Context, arg AlbumCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, albumCreate,
		arg.SpotifyID,
		arg.Name,
		arg.TrackAmount,
		arg.Popularity,
		arg.CoverID,
		arg.CoverUrl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const albumGetAll = `-- name: AlbumGetAll :many
SELECT id, spotify_id, name, track_amount, popularity, cover_url, cover_id, updated_at
FROM albums
`

func (q *Queries) AlbumGetAll(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, albumGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.TrackAmount,
			&i.Popularity,
			&i.CoverUrl,
			&i.CoverID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const albumGetBySpotify = `-- name: AlbumGetBySpotify :one
SELECT id, spotify_id, name, track_amount, popularity, cover_url, cover_id, updated_at
FROM albums
WHERE spotify_id = $1
`

func (q *Queries) AlbumGetBySpotify(ctx context.Context, spotifyID string) (Album, error) {
	row := q.db.QueryRow(ctx, albumGetBySpotify, spotifyID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Name,
		&i.TrackAmount,
		&i.Popularity,
		&i.CoverUrl,
		&i.CoverID,
		&i.UpdatedAt,
	)
	return i, err
}

const albumGetByUser = `-- name: AlbumGetByUser :many
SELECT a.id, a.spotify_id, a.name, a.track_amount, a.popularity, a.cover_url, a.cover_id, a.updated_at
FROM albums a
LEFT JOIN album_users au on au.album_id = a.id
WHERE au.user_id = $1
`

func (q *Queries) AlbumGetByUser(ctx context.Context, userID int32) ([]Album, error) {
	rows, err := q.db.Query(ctx, albumGetByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.TrackAmount,
			&i.Popularity,
			&i.CoverUrl,
			&i.CoverID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const albumUpdate = `-- name: AlbumUpdate :exec
UPDATE albums
SET 
  name = coalesce($2, name),
  track_amount = coalesce($3, track_amount),
  popularity = coalesce($4, popularity),
  cover_id = coalesce($5, cover_id),
  cover_url = coalesce($6, cover_url),
  updated_at = NOW()
WHERE id = $1
`

type AlbumUpdateParams struct {
	ID          int32
	Name        pgtype.Text
	TrackAmount pgtype.Int4
	Popularity  pgtype.Int4
	CoverID     pgtype.Text
	CoverUrl    pgtype.Text
}

func (q *Queries) AlbumUpdate(ctx context.Context, arg AlbumUpdateParams) error {
	_, err := q.db.Exec(ctx, albumUpdate,
		arg.ID,
		arg.Name,
		arg.TrackAmount,
		arg.Popularity,
		arg.CoverID,
		arg.CoverUrl,
	)
	return err
}
