// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_artist.sql

package sqlc

import (
	"context"
)

const albumArtistCreate = `-- name: AlbumArtistCreate :one
INSERT INTO album_artists (album_id, artist_id)
VALUES ($1, $2)
RETURNING id
`

type AlbumArtistCreateParams struct {
	AlbumID  int32
	ArtistID int32
}

func (q *Queries) AlbumArtistCreate(ctx context.Context, arg AlbumArtistCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, albumArtistCreate, arg.AlbumID, arg.ArtistID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const albumArtistDeleteByArtistAlbum = `-- name: AlbumArtistDeleteByArtistAlbum :exec
DELETE FROM album_artists
WHERE artist_id = $1 AND album_id = $2
`

type AlbumArtistDeleteByArtistAlbumParams struct {
	ArtistID int32
	AlbumID  int32
}

func (q *Queries) AlbumArtistDeleteByArtistAlbum(ctx context.Context, arg AlbumArtistDeleteByArtistAlbumParams) error {
	_, err := q.db.Exec(ctx, albumArtistDeleteByArtistAlbum, arg.ArtistID, arg.AlbumID)
	return err
}
