// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_user.sql

package sqlc

import (
	"context"
)

const albumUserCreate = `-- name: AlbumUserCreate :one
INSERT INTO album_users (user_id, album_id)
VALUES ($1, $2)
RETURNING id
`

type AlbumUserCreateParams struct {
	UserID  int32
	AlbumID int32
}

func (q *Queries) AlbumUserCreate(ctx context.Context, arg AlbumUserCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, albumUserCreate, arg.UserID, arg.AlbumID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const albumUserDeleteByUserAlbum = `-- name: AlbumUserDeleteByUserAlbum :exec
UPDATE album_users
SET deleted_at = NOW()
WHERE user_id = $1 AND album_id = $2
`

type AlbumUserDeleteByUserAlbumParams struct {
	UserID  int32
	AlbumID int32
}

func (q *Queries) AlbumUserDeleteByUserAlbum(ctx context.Context, arg AlbumUserDeleteByUserAlbumParams) error {
	_, err := q.db.Exec(ctx, albumUserDeleteByUserAlbum, arg.UserID, arg.AlbumID)
	return err
}
