// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist.sql

package sqlc

import (
	"context"
)

const artistCreate = `-- name: ArtistCreate :one
INSERT INTO artists (spotify_id, name, followers, popularity)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type ArtistCreateParams struct {
	SpotifyID  string
	Name       string
	Followers  int32
	Popularity int32
}

func (q *Queries) ArtistCreate(ctx context.Context, arg ArtistCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, artistCreate,
		arg.SpotifyID,
		arg.Name,
		arg.Followers,
		arg.Popularity,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const artistGetBySpotify = `-- name: ArtistGetBySpotify :one
SELECT id, spotify_id, name, followers, popularity
FROM artists
WHERE spotify_id = $1
`

func (q *Queries) ArtistGetBySpotify(ctx context.Context, spotifyID string) (Artist, error) {
	row := q.db.QueryRow(ctx, artistGetBySpotify, spotifyID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Name,
		&i.Followers,
		&i.Popularity,
	)
	return i, err
}

const artistUpdate = `-- name: ArtistUpdate :exec
UPDATE artists
SET name = $2, followers = $3, popularity = $4
WHERE id = $1
`

type ArtistUpdateParams struct {
	ID         int32
	Name       string
	Followers  int32
	Popularity int32
}

func (q *Queries) ArtistUpdate(ctx context.Context, arg ArtistUpdateParams) error {
	_, err := q.db.Exec(ctx, artistUpdate,
		arg.ID,
		arg.Name,
		arg.Followers,
		arg.Popularity,
	)
	return err
}
