// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: directory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const directoryCreate = `-- name: DirectoryCreate :one
INSERT INTO directories (user_id, name, parent_id)
VALUES ($1, $2, $3)
RETURNING id
`

type DirectoryCreateParams struct {
	UserID   int32
	Name     string
	ParentID pgtype.Int4
}

func (q *Queries) DirectoryCreate(ctx context.Context, arg DirectoryCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, directoryCreate, arg.UserID, arg.Name, arg.ParentID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const directoryDelete = `-- name: DirectoryDelete :exec
DELETE FROM directories
WHERE id = $1
`

func (q *Queries) DirectoryDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, directoryDelete, id)
	return err
}

const directoryGetByUser = `-- name: DirectoryGetByUser :many
SELECT id, user_id, name, parent_id
FROM directories d
WHERE d.user_id = $1
`

func (q *Queries) DirectoryGetByUser(ctx context.Context, userID int32) ([]Directory, error) {
	rows, err := q.db.Query(ctx, directoryGetByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Directory
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const directoryUpdate = `-- name: DirectoryUpdate :exec
UPDATE directories
SET name = $2, parent_id = $3
WHERE id = $1
`

type DirectoryUpdateParams struct {
	ID       int32
	Name     string
	ParentID pgtype.Int4
}

func (q *Queries) DirectoryUpdate(ctx context.Context, arg DirectoryUpdateParams) error {
	_, err := q.db.Exec(ctx, directoryUpdate, arg.ID, arg.Name, arg.ParentID)
	return err
}
