// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: directory_playlist.sql

package sqlc

import (
	"context"
)

const directoryPlaylistCreate = `-- name: DirectoryPlaylistCreate :one
INSERT INTO directory_playlists (directory_id, playlist_id)
VALUES ($1, $2)
RETURNING id
`

type DirectoryPlaylistCreateParams struct {
	DirectoryID int32
	PlaylistID  int32
}

func (q *Queries) DirectoryPlaylistCreate(ctx context.Context, arg DirectoryPlaylistCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, directoryPlaylistCreate, arg.DirectoryID, arg.PlaylistID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const directoryPlaylistDelete = `-- name: DirectoryPlaylistDelete :exec
DELETE FROM directory_playlists
WHERE id = $1
`

func (q *Queries) DirectoryPlaylistDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, directoryPlaylistDelete, id)
	return err
}

const directoryPlaylistGetByDirectory = `-- name: DirectoryPlaylistGetByDirectory :many
SELECT id, directory_id, playlist_id
FROM directory_playlists
WHERE directory_id = ANY($1::int[])
`

func (q *Queries) DirectoryPlaylistGetByDirectory(ctx context.Context, dollar_1 []int32) ([]DirectoryPlaylist, error) {
	rows, err := q.db.Query(ctx, directoryPlaylistGetByDirectory, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DirectoryPlaylist
	for rows.Next() {
		var i DirectoryPlaylist
		if err := rows.Scan(&i.ID, &i.DirectoryID, &i.PlaylistID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
