// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generator.sql

package sqlc

import (
	"context"
)

const generatorCreate = `-- name: GeneratorCreate :one
INSERT INTO generators (name, preset, parameters)
VALUES ($1, $2, $3)
RETURNING id
`

type GeneratorCreateParams struct {
	Name       string
	Preset     GeneratorPreset
	Parameters []byte
}

func (q *Queries) GeneratorCreate(ctx context.Context, arg GeneratorCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, generatorCreate, arg.Name, arg.Preset, arg.Parameters)
	var id int32
	err := row.Scan(&id)
	return id, err
}
