// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generator_track.sql

package sqlc

import (
	"context"
)

const generatorTrackCreateBatch = `-- name: GeneratorTrackCreateBatch :exec
INSERT INTO generator_tracks (generator_id, track_id)
VALUES (
  UNNEST($1::int[]),
  UNNEST($2::int[])
)
`

type GeneratorTrackCreateBatchParams struct {
	Column1 []int32
	Column2 []int32
}

func (q *Queries) GeneratorTrackCreateBatch(ctx context.Context, arg GeneratorTrackCreateBatchParams) error {
	_, err := q.db.Exec(ctx, generatorTrackCreateBatch, arg.Column1, arg.Column2)
	return err
}

const generatorTrackDeleteByGenerator = `-- name: GeneratorTrackDeleteByGenerator :exec
DELETE FROM generator_tracks
WHERE generator_id = $1
`

func (q *Queries) GeneratorTrackDeleteByGenerator(ctx context.Context, generatorID int32) error {
	_, err := q.db.Exec(ctx, generatorTrackDeleteByGenerator, generatorID)
	return err
}
