// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const historyCreate = `-- name: HistoryCreate :one
INSERT INTO history (user_id, track_id, played_at, album_id, artist_id, playlist_id, show_id, skipped)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type HistoryCreateParams struct {
	UserID     int32
	TrackID    int32
	PlayedAt   pgtype.Timestamptz
	AlbumID    pgtype.Int4
	ArtistID   pgtype.Int4
	PlaylistID pgtype.Int4
	ShowID     pgtype.Int4
	Skipped    pgtype.Bool
}

func (q *Queries) HistoryCreate(ctx context.Context, arg HistoryCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, historyCreate,
		arg.UserID,
		arg.TrackID,
		arg.PlayedAt,
		arg.AlbumID,
		arg.ArtistID,
		arg.PlaylistID,
		arg.ShowID,
		arg.Skipped,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const historyCreateBatch = `-- name: HistoryCreateBatch :exec
INSERT INTO history (user_id, track_id, played_at, skipped)
VALUES (
  UNNEST($1::int[]),
  UNNEST($2::int[]),
  UNNEST($3::timestamptz[]),
  UNNEST($4::boolean[])
)
`

type HistoryCreateBatchParams struct {
	Column1 []int32
	Column2 []int32
	Column3 []pgtype.Timestamptz
	Column4 []bool
}

func (q *Queries) HistoryCreateBatch(ctx context.Context, arg HistoryCreateBatchParams) error {
	_, err := q.db.Exec(ctx, historyCreateBatch,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const historyDeleteUserOlder = `-- name: HistoryDeleteUserOlder :exec
DELETE FROM history
WHERE user_id = $1 AND played_at < $2
`

type HistoryDeleteUserOlderParams struct {
	UserID   int32
	PlayedAt pgtype.Timestamptz
}

func (q *Queries) HistoryDeleteUserOlder(ctx context.Context, arg HistoryDeleteUserOlderParams) error {
	_, err := q.db.Exec(ctx, historyDeleteUserOlder, arg.UserID, arg.PlayedAt)
	return err
}

const historyGetPopulatedFiltered = `-- name: HistoryGetPopulatedFiltered :many
SELECT h.id, h.user_id, h.track_id, h.played_at, h.album_id, h.artist_id, h.playlist_id, h.show_id, h.skipped, t.id, t.spotify_id, t.name, t.popularity, t.updated_at, t.duration_ms
FROM history h
LEFT JOIN tracks t ON t.id = h.track_id
WHERE 
  h.user_id = $1::int AND
  (h.played_at >= $2::timestamptz OR NOT $5) AND 
  (h.played_at <= $3::timestamptz OR NOT $6) AND
  (h.skipped = $4::boolean OR NOT $7)
ORDER BY h.played_at DESC
`

type HistoryGetPopulatedFilteredParams struct {
	Column1       int32
	Column2       pgtype.Timestamptz
	Column3       pgtype.Timestamptz
	Column4       bool
	FilterStart   interface{}
	FilterEnd     interface{}
	FilterSkipped interface{}
}

type HistoryGetPopulatedFilteredRow struct {
	History History
	Track   Track
}

func (q *Queries) HistoryGetPopulatedFiltered(ctx context.Context, arg HistoryGetPopulatedFilteredParams) ([]HistoryGetPopulatedFilteredRow, error) {
	rows, err := q.db.Query(ctx, historyGetPopulatedFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.FilterStart,
		arg.FilterEnd,
		arg.FilterSkipped,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryGetPopulatedFilteredRow
	for rows.Next() {
		var i HistoryGetPopulatedFilteredRow
		if err := rows.Scan(
			&i.History.ID,
			&i.History.UserID,
			&i.History.TrackID,
			&i.History.PlayedAt,
			&i.History.AlbumID,
			&i.History.ArtistID,
			&i.History.PlaylistID,
			&i.History.ShowID,
			&i.History.Skipped,
			&i.Track.ID,
			&i.Track.SpotifyID,
			&i.Track.Name,
			&i.Track.Popularity,
			&i.Track.UpdatedAt,
			&i.Track.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyGetPopulatedFilteredPaginated = `-- name: HistoryGetPopulatedFilteredPaginated :many
SELECT h.id, h.user_id, h.track_id, h.played_at, h.album_id, h.artist_id, h.playlist_id, h.show_id, h.skipped, t.id, t.spotify_id, t.name, t.popularity, t.updated_at, t.duration_ms, count(*) FILTER (WHERE h.user_id = $1::int AND (h.skipped = $7::boolean OR NOT $8)) OVER  (PARTITION BY h.track_id) AS play_count
FROM history h
LEFT JOIN tracks t ON t.id = h.track_id
WHERE 
  h.user_id = $1::int AND
  (h.played_at >= $4::timestamptz OR NOT $9) AND 
  (h.played_at <= $5::timestamptz OR NOT $10) AND
  (h.skipped = $6::boolean OR NOT $11)
ORDER BY h.played_at DESC
LIMIT $2 OFFSET $3
`

type HistoryGetPopulatedFilteredPaginatedParams struct {
	Column1         int32
	Limit           int32
	Offset          int32
	Column4         pgtype.Timestamptz
	Column5         pgtype.Timestamptz
	Column6         bool
	Column7         bool
	FilterPlayCount interface{}
	FilterStart     interface{}
	FilterEnd       interface{}
	FilterSkipped   interface{}
}

type HistoryGetPopulatedFilteredPaginatedRow struct {
	History   History
	Track     Track
	PlayCount int64
}

func (q *Queries) HistoryGetPopulatedFilteredPaginated(ctx context.Context, arg HistoryGetPopulatedFilteredPaginatedParams) ([]HistoryGetPopulatedFilteredPaginatedRow, error) {
	rows, err := q.db.Query(ctx, historyGetPopulatedFilteredPaginated,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.FilterPlayCount,
		arg.FilterStart,
		arg.FilterEnd,
		arg.FilterSkipped,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryGetPopulatedFilteredPaginatedRow
	for rows.Next() {
		var i HistoryGetPopulatedFilteredPaginatedRow
		if err := rows.Scan(
			&i.History.ID,
			&i.History.UserID,
			&i.History.TrackID,
			&i.History.PlayedAt,
			&i.History.AlbumID,
			&i.History.ArtistID,
			&i.History.PlaylistID,
			&i.History.ShowID,
			&i.History.Skipped,
			&i.Track.ID,
			&i.Track.SpotifyID,
			&i.Track.Name,
			&i.Track.Popularity,
			&i.Track.UpdatedAt,
			&i.Track.DurationMs,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyGetPreviousPopulated = `-- name: HistoryGetPreviousPopulated :one
SELECT h.id, h.user_id, h.track_id, h.played_at, h.album_id, h.artist_id, h.playlist_id, h.show_id, h.skipped, t.id, t.spotify_id, t.name, t.popularity, t.updated_at, t.duration_ms
FROM history h
LEFT JOIN tracks t ON t.id = h.track_id
WHERE h.played_at < $1 AND h.user_id = $2
ORDER BY h.played_at DESC
LIMIT 1
`

type HistoryGetPreviousPopulatedParams struct {
	PlayedAt pgtype.Timestamptz
	UserID   int32
}

type HistoryGetPreviousPopulatedRow struct {
	History History
	Track   Track
}

func (q *Queries) HistoryGetPreviousPopulated(ctx context.Context, arg HistoryGetPreviousPopulatedParams) (HistoryGetPreviousPopulatedRow, error) {
	row := q.db.QueryRow(ctx, historyGetPreviousPopulated, arg.PlayedAt, arg.UserID)
	var i HistoryGetPreviousPopulatedRow
	err := row.Scan(
		&i.History.ID,
		&i.History.UserID,
		&i.History.TrackID,
		&i.History.PlayedAt,
		&i.History.AlbumID,
		&i.History.ArtistID,
		&i.History.PlaylistID,
		&i.History.ShowID,
		&i.History.Skipped,
		&i.Track.ID,
		&i.Track.SpotifyID,
		&i.Track.Name,
		&i.Track.Popularity,
		&i.Track.UpdatedAt,
		&i.Track.DurationMs,
	)
	return i, err
}

const historyGetSkippedNullPopulated = `-- name: HistoryGetSkippedNullPopulated :many
SELECT h.id, h.user_id, h.track_id, h.played_at, h.album_id, h.artist_id, h.playlist_id, h.show_id, h.skipped, t.id, t.spotify_id, t.name, t.popularity, t.updated_at, t.duration_ms
FROM history h
LEFT JOIN tracks t ON t.id = h.track_id
WHERE h.skipped IS NULL AND h.user_id = $1
ORDER BY played_at ASC
`

type HistoryGetSkippedNullPopulatedRow struct {
	History History
	Track   Track
}

func (q *Queries) HistoryGetSkippedNullPopulated(ctx context.Context, userID int32) ([]HistoryGetSkippedNullPopulatedRow, error) {
	rows, err := q.db.Query(ctx, historyGetSkippedNullPopulated, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryGetSkippedNullPopulatedRow
	for rows.Next() {
		var i HistoryGetSkippedNullPopulatedRow
		if err := rows.Scan(
			&i.History.ID,
			&i.History.UserID,
			&i.History.TrackID,
			&i.History.PlayedAt,
			&i.History.AlbumID,
			&i.History.ArtistID,
			&i.History.PlaylistID,
			&i.History.ShowID,
			&i.History.Skipped,
			&i.Track.ID,
			&i.Track.SpotifyID,
			&i.Track.Name,
			&i.Track.Popularity,
			&i.Track.UpdatedAt,
			&i.Track.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyUpdate = `-- name: HistoryUpdate :exec
UPDATE history
SET 
  played_at = coalesce($2, played_at),
  skipped = coalesce($3, skipped)
WHERE id = $1
`

type HistoryUpdateParams struct {
	ID       int32
	PlayedAt pgtype.Timestamptz
	Skipped  pgtype.Bool
}

func (q *Queries) HistoryUpdate(ctx context.Context, arg HistoryUpdateParams) error {
	_, err := q.db.Exec(ctx, historyUpdate, arg.ID, arg.PlayedAt, arg.Skipped)
	return err
}
