// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const historyCreate = `-- name: HistoryCreate :one
INSERT INTO history (user_id, track_id, played_at, album_id, artist_id, playlist_id, show_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type HistoryCreateParams struct {
	UserID     int32
	TrackID    int32
	PlayedAt   pgtype.Timestamptz
	AlbumID    pgtype.Int4
	ArtistID   pgtype.Int4
	PlaylistID pgtype.Int4
	ShowID     pgtype.Int4
}

func (q *Queries) HistoryCreate(ctx context.Context, arg HistoryCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, historyCreate,
		arg.UserID,
		arg.TrackID,
		arg.PlayedAt,
		arg.AlbumID,
		arg.ArtistID,
		arg.PlaylistID,
		arg.ShowID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const historyGetByPlaylist = `-- name: HistoryGetByPlaylist :many
SELECT id, user_id, track_id, played_at, album_id, artist_id, playlist_id, show_id
FROM history
WHERE playlist_id = $1
`

func (q *Queries) HistoryGetByPlaylist(ctx context.Context, playlistID pgtype.Int4) ([]History, error) {
	rows, err := q.db.Query(ctx, historyGetByPlaylist, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.PlayedAt,
			&i.AlbumID,
			&i.ArtistID,
			&i.PlaylistID,
			&i.ShowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyGetLatestByUser = `-- name: HistoryGetLatestByUser :one
SELECT id, user_id, track_id, played_at, album_id, artist_id, playlist_id, show_id
FROM history
WHERE user_id = $1
ORDER BY played_at DESC
LIMIT 1
`

func (q *Queries) HistoryGetLatestByUser(ctx context.Context, userID int32) (History, error) {
	row := q.db.QueryRow(ctx, historyGetLatestByUser, userID)
	var i History
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.PlayedAt,
		&i.AlbumID,
		&i.ArtistID,
		&i.PlaylistID,
		&i.ShowID,
	)
	return i, err
}
