// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const historyCreate = `-- name: HistoryCreate :one
INSERT INTO history (user_id, track_id, played_at, album_id, artist_id, playlist_id, show_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type HistoryCreateParams struct {
	UserID     int32
	TrackID    int32
	PlayedAt   pgtype.Timestamptz
	AlbumID    pgtype.Int4
	ArtistID   pgtype.Int4
	PlaylistID pgtype.Int4
	ShowID     pgtype.Int4
}

func (q *Queries) HistoryCreate(ctx context.Context, arg HistoryCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, historyCreate,
		arg.UserID,
		arg.TrackID,
		arg.PlayedAt,
		arg.AlbumID,
		arg.ArtistID,
		arg.PlaylistID,
		arg.ShowID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const historyCreateBatch = `-- name: HistoryCreateBatch :exec
INSERT INTO history (user_id, track_id, played_at)
VALUES (
  UNNEST($1::int[]),
  UNNEST($2::int[]),
  UNNEST($3::timestamptz[])
)
`

type HistoryCreateBatchParams struct {
	Column1 []int32
	Column2 []int32
	Column3 []pgtype.Timestamptz
}

func (q *Queries) HistoryCreateBatch(ctx context.Context, arg HistoryCreateBatchParams) error {
	_, err := q.db.Exec(ctx, historyCreateBatch, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const historyDeleteUserOlder = `-- name: HistoryDeleteUserOlder :exec
DELETE FROM history
WHERE user_id = $1 AND played_at < $2
`

type HistoryDeleteUserOlderParams struct {
	UserID   int32
	PlayedAt pgtype.Timestamptz
}

func (q *Queries) HistoryDeleteUserOlder(ctx context.Context, arg HistoryDeleteUserOlderParams) error {
	_, err := q.db.Exec(ctx, historyDeleteUserOlder, arg.UserID, arg.PlayedAt)
	return err
}

const historyGetLatestByUser = `-- name: HistoryGetLatestByUser :one
SELECT id, user_id, track_id, played_at, album_id, artist_id, playlist_id, show_id
FROM history
WHERE user_id = $1
ORDER BY played_at DESC
LIMIT 1
`

func (q *Queries) HistoryGetLatestByUser(ctx context.Context, userID int32) (History, error) {
	row := q.db.QueryRow(ctx, historyGetLatestByUser, userID)
	var i History
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.PlayedAt,
		&i.AlbumID,
		&i.ArtistID,
		&i.PlaylistID,
		&i.ShowID,
	)
	return i, err
}

const historyGetPopulatedFiltered = `-- name: HistoryGetPopulatedFiltered :many
SELECT h.id, h.user_id, h.track_id, h.played_at, h.album_id, h.artist_id, h.playlist_id, h.show_id, t.id, t.spotify_id, t.name, t.popularity, t.updated_at
FROM history h
LEFT JOIN tracks t ON t.id = h.track_id
WHERE 
  h.user_id = $1::int AND
  (h.played_at >= $4::timestamptz OR NOT $6) AND 
  (h.played_at <= $5::timestamptz OR NOT $7)
ORDER BY h.played_at DESC
LIMIT $2 OFFSET $3
`

type HistoryGetPopulatedFilteredParams struct {
	Column1     int32
	Limit       int32
	Offset      int32
	Column4     pgtype.Timestamptz
	Column5     pgtype.Timestamptz
	FilterStart interface{}
	FilterEnd   interface{}
}

type HistoryGetPopulatedFilteredRow struct {
	History History
	Track   Track
}

func (q *Queries) HistoryGetPopulatedFiltered(ctx context.Context, arg HistoryGetPopulatedFilteredParams) ([]HistoryGetPopulatedFilteredRow, error) {
	rows, err := q.db.Query(ctx, historyGetPopulatedFiltered,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
		arg.FilterStart,
		arg.FilterEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryGetPopulatedFilteredRow
	for rows.Next() {
		var i HistoryGetPopulatedFilteredRow
		if err := rows.Scan(
			&i.History.ID,
			&i.History.UserID,
			&i.History.TrackID,
			&i.History.PlayedAt,
			&i.History.AlbumID,
			&i.History.ArtistID,
			&i.History.PlaylistID,
			&i.History.ShowID,
			&i.Track.ID,
			&i.Track.SpotifyID,
			&i.Track.Name,
			&i.Track.Popularity,
			&i.Track.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
