// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const linkCreate = `-- name: LinkCreate :one
INSERT INTO links (source_directory_id, source_playlist_id, target_directory_id, target_playlist_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type LinkCreateParams struct {
	SourceDirectoryID pgtype.Int4
	SourcePlaylistID  pgtype.Int4
	TargetDirectoryID pgtype.Int4
	TargetPlaylistID  pgtype.Int4
}

func (q *Queries) LinkCreate(ctx context.Context, arg LinkCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, linkCreate,
		arg.SourceDirectoryID,
		arg.SourcePlaylistID,
		arg.TargetDirectoryID,
		arg.TargetPlaylistID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const linkDelete = `-- name: LinkDelete :exec
DELETE FROM links
WHERE id = $1
`

func (q *Queries) LinkDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, linkDelete, id)
	return err
}

const linkGetByUser = `-- name: LinkGetByUser :many
SELECT l.id, l.source_directory_id, l.source_playlist_id, l.target_directory_id, l.target_playlist_id
FROM links l
LEFT JOIN directories d ON d.id = l.source_directory_id
LEFT JOIN playlists p ON p.id = l.source_playlist_id
LEFT JOIN playlist_users pu ON pu.playlist_id = p.id
WHERE d.user_id = $1 OR (pu.user_id = $1 AND pu.deleted_at IS NULL)
`

func (q *Queries) LinkGetByUser(ctx context.Context, userID int32) ([]Link, error) {
	rows, err := q.db.Query(ctx, linkGetByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.SourceDirectoryID,
			&i.SourcePlaylistID,
			&i.TargetDirectoryID,
			&i.TargetPlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkUpdate = `-- name: LinkUpdate :exec
UPDATE links
SET source_directory_id = $2, source_playlist_id = $3, target_directory_id = $4, target_playlist_id = $5
WHERE id = $1
`

type LinkUpdateParams struct {
	ID                int32
	SourceDirectoryID pgtype.Int4
	SourcePlaylistID  pgtype.Int4
	TargetDirectoryID pgtype.Int4
	TargetPlaylistID  pgtype.Int4
}

func (q *Queries) LinkUpdate(ctx context.Context, arg LinkUpdateParams) error {
	_, err := q.db.Exec(ctx, linkUpdate,
		arg.ID,
		arg.SourceDirectoryID,
		arg.SourcePlaylistID,
		arg.TargetDirectoryID,
		arg.TargetPlaylistID,
	)
	return err
}
