// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Directory struct {
	ID       int32
	UserID   int32
	Name     string
	ParentID pgtype.Int4
}

type DirectoryPlaylist struct {
	ID          int32
	DirectoryID int32
	PlaylistID  int32
}

type Playlist struct {
	ID            int32
	UserID        int32
	SpotifyID     string
	OwnerUid      string
	Name          string
	Description   pgtype.Text
	Public        bool
	Tracks        int32
	Collaborative bool
}

type Setting struct {
	ID          int32
	UserID      int32
	LastUpdated pgtype.Timestamptz
}

type User struct {
	ID          int32
	Uid         string
	Name        string
	DisplayName pgtype.Text
	Email       string
}
