// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskResult string

const (
	TaskResultSuccess TaskResult = "success"
	TaskResultFailed  TaskResult = "failed"
)

func (e *TaskResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskResult(s)
	case string:
		*e = TaskResult(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskResult: %T", src)
	}
	return nil
}

type NullTaskResult struct {
	TaskResult TaskResult
	Valid      bool // Valid is true if TaskResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskResult) Scan(value interface{}) error {
	if value == nil {
		ns.TaskResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskResult), nil
}

type Album struct {
	ID          int32
	SpotifyID   string
	Name        pgtype.Text
	TrackAmount pgtype.Int4
	Popularity  pgtype.Int4
	CoverUrl    pgtype.Text
	CoverID     pgtype.Text
	UpdatedAt   pgtype.Timestamptz
}

type AlbumArtist struct {
	ID       int32
	ArtistID int32
	AlbumID  int32
}

type AlbumUser struct {
	ID        int32
	UserID    int32
	AlbumID   int32
	DeletedAt pgtype.Timestamptz
}

type Artist struct {
	ID         int32
	SpotifyID  string
	Name       pgtype.Text
	Followers  pgtype.Int4
	Popularity pgtype.Int4
	CoverUrl   pgtype.Text
	CoverID    pgtype.Text
	UpdatedAt  pgtype.Timestamptz
}

type Directory struct {
	ID       int32
	UserID   int32
	Name     string
	ParentID pgtype.Int4
}

type DirectoryPlaylist struct {
	ID          int32
	DirectoryID int32
	PlaylistID  int32
}

type Generator struct {
	ID              int32
	UserID          int32
	Name            string
	Description     pgtype.Text
	PlaylistID      pgtype.Int4
	Interval        pgtype.Int8
	SpotifyOutdated bool
	Parameters      []byte
	UpdatedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type GeneratorTrack struct {
	ID          int32
	GeneratorID int32
	TrackID     int32
}

type History struct {
	ID         int32
	UserID     int32
	TrackID    int32
	PlayedAt   pgtype.Timestamptz
	AlbumID    pgtype.Int4
	ArtistID   pgtype.Int4
	PlaylistID pgtype.Int4
	ShowID     pgtype.Int4
	Skipped    pgtype.Bool
}

type Link struct {
	ID                int32
	SourceDirectoryID pgtype.Int4
	SourcePlaylistID  pgtype.Int4
	TargetDirectoryID pgtype.Int4
	TargetPlaylistID  pgtype.Int4
}

type Playlist struct {
	ID            int32
	SpotifyID     string
	Name          pgtype.Text
	Description   pgtype.Text
	Public        pgtype.Bool
	TrackAmount   pgtype.Int4
	Collaborative pgtype.Bool
	CoverID       pgtype.Text
	CoverUrl      pgtype.Text
	OwnerID       pgtype.Int4
	UpdatedAt     pgtype.Timestamptz
	SnapshotID    pgtype.Text
}

type PlaylistTrack struct {
	ID         int32
	PlaylistID int32
	TrackID    int32
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type PlaylistUser struct {
	ID         int32
	UserID     int32
	PlaylistID int32
	DeletedAt  pgtype.Timestamptz
}

type Show struct {
	ID            int32
	SpotifyID     string
	EpisodeAmount pgtype.Int4
	Name          pgtype.Text
	CoverUrl      pgtype.Text
	CoverID       pgtype.Text
	UpdatedAt     pgtype.Timestamptz
}

type ShowUser struct {
	ID        int32
	UserID    int32
	ShowID    int32
	DeletedAt pgtype.Timestamptz
}

type Task struct {
	Uid       string
	Name      string
	Active    bool
	Recurring bool
}

type TaskRun struct {
	ID       int32
	TaskUid  string
	UserID   int32
	RunAt    pgtype.Timestamptz
	Result   TaskResult
	Error    pgtype.Text
	Duration int64
	Message  pgtype.Text
}

type Track struct {
	ID         int32
	SpotifyID  string
	Name       pgtype.Text
	Popularity pgtype.Int4
	UpdatedAt  pgtype.Timestamptz
	DurationMs pgtype.Int4
}

type TrackArtist struct {
	ID       int32
	ArtistID int32
	TrackID  int32
}

type User struct {
	ID          int32
	Uid         string
	Name        string
	DisplayName pgtype.Text
	Email       string
}
