// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskResult string

const (
	TaskResultSuccess TaskResult = "success"
	TaskResultFailed  TaskResult = "failed"
)

func (e *TaskResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskResult(s)
	case string:
		*e = TaskResult(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskResult: %T", src)
	}
	return nil
}

type NullTaskResult struct {
	TaskResult TaskResult
	Valid      bool // Valid is true if TaskResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskResult) Scan(value interface{}) error {
	if value == nil {
		ns.TaskResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskResult), nil
}

type Album struct {
	ID          int32
	SpotifyID   string
	Name        string
	TrackAmount int32
	Popularity  int32
}

type Artist struct {
	ID         int32
	SpotifyID  string
	Name       string
	Followers  int32
	Popularity int32
}

type Directory struct {
	ID       int32
	UserID   int32
	Name     string
	ParentID pgtype.Int4
}

type DirectoryPlaylist struct {
	ID          int32
	DirectoryID int32
	PlaylistID  int32
}

type History struct {
	ID         int32
	UserID     int32
	TrackID    int32
	PlayedAt   pgtype.Timestamptz
	AlbumID    pgtype.Int4
	ArtistID   pgtype.Int4
	PlaylistID pgtype.Int4
	ShowID     pgtype.Int4
}

type Link struct {
	ID                int32
	SourceDirectoryID pgtype.Int4
	SourcePlaylistID  pgtype.Int4
	TargetDirectoryID pgtype.Int4
	TargetPlaylistID  pgtype.Int4
}

type Playlist struct {
	ID            int32
	UserID        int32
	SpotifyID     string
	OwnerUid      string
	Name          string
	Description   pgtype.Text
	Public        bool
	TrackAmount   int32
	Collaborative bool
	CoverID       pgtype.Text
	CoverUrl      pgtype.Text
}

type PlaylistTrack struct {
	ID         int32
	PlaylistID int32
	TrackID    int32
}

type Show struct {
	ID            int32
	SpotifyID     string
	EpisodeAmount int32
	Name          string
}

type Task struct {
	Uid    string
	Name   string
	Active bool
}

type TaskRun struct {
	ID       int32
	TaskUid  string
	UserID   int32
	RunAt    pgtype.Timestamptz
	Result   TaskResult
	Error    pgtype.Text
	Duration int64
	Message  pgtype.Text
}

type Track struct {
	ID         int32
	SpotifyID  string
	Name       string
	Popularity int32
}

type User struct {
	ID          int32
	Uid         string
	Name        string
	DisplayName pgtype.Text
	Email       string
}
