// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist_user.sql

package sqlc

import (
	"context"
)

const playlistUserCreate = `-- name: PlaylistUserCreate :one
INSERT INTO playlist_users (user_id, playlist_id)
VALUES ($1, $2)
RETURNING id
`

type PlaylistUserCreateParams struct {
	UserID     int32
	PlaylistID int32
}

func (q *Queries) PlaylistUserCreate(ctx context.Context, arg PlaylistUserCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, playlistUserCreate, arg.UserID, arg.PlaylistID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const playlistUserDeleteByUserPlaylist = `-- name: PlaylistUserDeleteByUserPlaylist :exec
UPDATE playlist_users
SET deleted_at = NOW()
WHERE user_id = $1 AND playlist_id = $2
`

type PlaylistUserDeleteByUserPlaylistParams struct {
	UserID     int32
	PlaylistID int32
}

func (q *Queries) PlaylistUserDeleteByUserPlaylist(ctx context.Context, arg PlaylistUserDeleteByUserPlaylistParams) error {
	_, err := q.db.Exec(ctx, playlistUserDeleteByUserPlaylist, arg.UserID, arg.PlaylistID)
	return err
}
