// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist_track.sql

package sqlc

import (
	"context"
)

const playlistTrackCreate = `-- name: PlaylistTrackCreate :one
INSERT INTO playlist_tracks (playlist_id, track_id)
VALUES ($1, $2)
RETURNING id
`

type PlaylistTrackCreateParams struct {
	PlaylistID int32
	TrackID    int32
}

func (q *Queries) PlaylistTrackCreate(ctx context.Context, arg PlaylistTrackCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, playlistTrackCreate, arg.PlaylistID, arg.TrackID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const playlistTrackDeleteByPlaylistTrack = `-- name: PlaylistTrackDeleteByPlaylistTrack :exec
UPDATE playlist_tracks
SET deleted_at = NOW()
WHERE playlist_id = $1 AND track_id = $2
`

type PlaylistTrackDeleteByPlaylistTrackParams struct {
	PlaylistID int32
	TrackID    int32
}

func (q *Queries) PlaylistTrackDeleteByPlaylistTrack(ctx context.Context, arg PlaylistTrackDeleteByPlaylistTrackParams) error {
	_, err := q.db.Exec(ctx, playlistTrackDeleteByPlaylistTrack, arg.PlaylistID, arg.TrackID)
	return err
}
