// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist_track.sql

package sqlc

import (
	"context"
)

const playlistTrackCreate = `-- name: PlaylistTrackCreate :one
INSERT INTO playlist_tracks (playlist_id, track_id)
VALUES ($1, $2)
RETURNING id
`

type PlaylistTrackCreateParams struct {
	PlaylistID int32
	TrackID    int32
}

func (q *Queries) PlaylistTrackCreate(ctx context.Context, arg PlaylistTrackCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, playlistTrackCreate, arg.PlaylistID, arg.TrackID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const playlistTrackDeleteByPlaylistTrack = `-- name: PlaylistTrackDeleteByPlaylistTrack :exec
UPDATE playlist_tracks
SET deleted_at = NOW()
WHERE playlist_id = $1 AND track_id = $2
`

type PlaylistTrackDeleteByPlaylistTrackParams struct {
	PlaylistID int32
	TrackID    int32
}

func (q *Queries) PlaylistTrackDeleteByPlaylistTrack(ctx context.Context, arg PlaylistTrackDeleteByPlaylistTrackParams) error {
	_, err := q.db.Exec(ctx, playlistTrackDeleteByPlaylistTrack, arg.PlaylistID, arg.TrackID)
	return err
}

const playlistTrackGetByPlaylistIds = `-- name: PlaylistTrackGetByPlaylistIds :many
SELECT id, playlist_id, track_id, deleted_at, created_at
FROM playlist_tracks
WHERE playlist_id = ANY($1::int[])
`

func (q *Queries) PlaylistTrackGetByPlaylistIds(ctx context.Context, dollar_1 []int32) ([]PlaylistTrack, error) {
	rows, err := q.db.Query(ctx, playlistTrackGetByPlaylistIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaylistTrack
	for rows.Next() {
		var i PlaylistTrack
		if err := rows.Scan(
			&i.ID,
			&i.PlaylistID,
			&i.TrackID,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
