// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const settingCreate = `-- name: SettingCreate :one
INSERT INTO settings (user_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) SettingCreate(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, settingCreate, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const settingGetByUser = `-- name: SettingGetByUser :one
SELECT id, user_id, last_updated
FROM settings
WHERE user_id = $1
`

func (q *Queries) SettingGetByUser(ctx context.Context, userID int32) (Setting, error) {
	row := q.db.QueryRow(ctx, settingGetByUser, userID)
	var i Setting
	err := row.Scan(&i.ID, &i.UserID, &i.LastUpdated)
	return i, err
}

const settingUpdateByUser = `-- name: SettingUpdateByUser :exec
UPDATE settings
SET last_updated = $2
WHERE user_id = $1
`

type SettingUpdateByUserParams struct {
	UserID      int32
	LastUpdated pgtype.Timestamptz
}

func (q *Queries) SettingUpdateByUser(ctx context.Context, arg SettingUpdateByUserParams) error {
	_, err := q.db.Exec(ctx, settingUpdateByUser, arg.UserID, arg.LastUpdated)
	return err
}
