// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: show.sql

package sqlc

import (
	"context"
)

const showCreate = `-- name: ShowCreate :one
INSERT INTO shows (spotify_id, episode_amount, name)
VALUES ($1, $2, $3)
RETURNING id
`

type ShowCreateParams struct {
	SpotifyID     string
	EpisodeAmount int32
	Name          string
}

func (q *Queries) ShowCreate(ctx context.Context, arg ShowCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, showCreate, arg.SpotifyID, arg.EpisodeAmount, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const showGetBySpotify = `-- name: ShowGetBySpotify :one
SELECT id, spotify_id, episode_amount, name
FROM shows
WHERE spotify_id = $1
`

func (q *Queries) ShowGetBySpotify(ctx context.Context, spotifyID string) (Show, error) {
	row := q.db.QueryRow(ctx, showGetBySpotify, spotifyID)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.EpisodeAmount,
		&i.Name,
	)
	return i, err
}

const showUpdate = `-- name: ShowUpdate :exec
UPDATE shows
SET name = $2, episode_amount = $3
WHERE id = $1
`

type ShowUpdateParams struct {
	ID            int32
	Name          string
	EpisodeAmount int32
}

func (q *Queries) ShowUpdate(ctx context.Context, arg ShowUpdateParams) error {
	_, err := q.db.Exec(ctx, showUpdate, arg.ID, arg.Name, arg.EpisodeAmount)
	return err
}
