// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: show.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const showCreate = `-- name: ShowCreate :one
INSERT INTO shows (spotify_id, episode_amount, name, cover_id, cover_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type ShowCreateParams struct {
	SpotifyID     string
	EpisodeAmount pgtype.Int4
	Name          pgtype.Text
	CoverID       pgtype.Text
	CoverUrl      pgtype.Text
}

func (q *Queries) ShowCreate(ctx context.Context, arg ShowCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, showCreate,
		arg.SpotifyID,
		arg.EpisodeAmount,
		arg.Name,
		arg.CoverID,
		arg.CoverUrl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const showGetAll = `-- name: ShowGetAll :many
SELECT id, spotify_id, episode_amount, name, cover_url, cover_id, updated_at
FROM shows
`

func (q *Queries) ShowGetAll(ctx context.Context) ([]Show, error) {
	rows, err := q.db.Query(ctx, showGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.EpisodeAmount,
			&i.Name,
			&i.CoverUrl,
			&i.CoverID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showGetBySpotify = `-- name: ShowGetBySpotify :one
SELECT id, spotify_id, episode_amount, name, cover_url, cover_id, updated_at
FROM shows
WHERE spotify_id = $1
`

func (q *Queries) ShowGetBySpotify(ctx context.Context, spotifyID string) (Show, error) {
	row := q.db.QueryRow(ctx, showGetBySpotify, spotifyID)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.EpisodeAmount,
		&i.Name,
		&i.CoverUrl,
		&i.CoverID,
		&i.UpdatedAt,
	)
	return i, err
}

const showGetByUser = `-- name: ShowGetByUser :many
SELECT s.id, s.spotify_id, s.episode_amount, s.name, s.cover_url, s.cover_id, s.updated_at
FROM shows s
LEFT JOIN show_users su on su.show_id = s.id
WHERE su.user_id = $1 AND su.deleted_at IS NULL
`

func (q *Queries) ShowGetByUser(ctx context.Context, userID int32) ([]Show, error) {
	rows, err := q.db.Query(ctx, showGetByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.EpisodeAmount,
			&i.Name,
			&i.CoverUrl,
			&i.CoverID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showUpdate = `-- name: ShowUpdate :exec
UPDATE shows
SET
  name = coalesce($2, name),
  episode_amount = coalesce($3, episode_amount),
  cover_id = coalesce($4, cover_id),
  cover_url = coalesce($5, cover_url),
  updated_at = NOW()
WHERE id = $1
`

type ShowUpdateParams struct {
	ID            int32
	Name          pgtype.Text
	EpisodeAmount pgtype.Int4
	CoverID       pgtype.Text
	CoverUrl      pgtype.Text
}

func (q *Queries) ShowUpdate(ctx context.Context, arg ShowUpdateParams) error {
	_, err := q.db.Exec(ctx, showUpdate,
		arg.ID,
		arg.Name,
		arg.EpisodeAmount,
		arg.CoverID,
		arg.CoverUrl,
	)
	return err
}
