// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: show_user.sql

package sqlc

import (
	"context"
)

const showUserCreate = `-- name: ShowUserCreate :one
INSERT INTO show_users (user_id, show_id)
VALUES ($1, $2)
RETURNING id
`

type ShowUserCreateParams struct {
	UserID int32
	ShowID int32
}

func (q *Queries) ShowUserCreate(ctx context.Context, arg ShowUserCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, showUserCreate, arg.UserID, arg.ShowID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const showUserDeleteByUserShow = `-- name: ShowUserDeleteByUserShow :exec
UPDATE show_users
SET deleted_at = NOW()
WHERE user_id = $1 AND show_id = $2
`

type ShowUserDeleteByUserShowParams struct {
	UserID int32
	ShowID int32
}

func (q *Queries) ShowUserDeleteByUserShow(ctx context.Context, arg ShowUserDeleteByUserShowParams) error {
	_, err := q.db.Exec(ctx, showUserDeleteByUserShow, arg.UserID, arg.ShowID)
	return err
}
