// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_run.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const taskRunCreate = `-- name: TaskRunCreate :one
INSERT INTO task_runs (task_uid, user_id, run_at, result, error, duration)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type TaskRunCreateParams struct {
	TaskUid  string
	UserID   pgtype.Int4
	RunAt    pgtype.Timestamptz
	Result   TaskResult
	Error    pgtype.Text
	Duration int64
}

func (q *Queries) TaskRunCreate(ctx context.Context, arg TaskRunCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, taskRunCreate,
		arg.TaskUid,
		arg.UserID,
		arg.RunAt,
		arg.Result,
		arg.Error,
		arg.Duration,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
