// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track_artist.sql

package sqlc

import (
	"context"
)

const trackArtistCreate = `-- name: TrackArtistCreate :one
INSERT INTO track_artists (track_id, artist_id)
VALUES ($1, $2)
RETURNING id
`

type TrackArtistCreateParams struct {
	TrackID  int32
	ArtistID int32
}

func (q *Queries) TrackArtistCreate(ctx context.Context, arg TrackArtistCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, trackArtistCreate, arg.TrackID, arg.ArtistID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const trackArtistDeleteByArtistTrack = `-- name: TrackArtistDeleteByArtistTrack :exec
DELETE FROM track_artists
WHERE artist_id = $1 AND track_id = $2
`

type TrackArtistDeleteByArtistTrackParams struct {
	ArtistID int32
	TrackID  int32
}

func (q *Queries) TrackArtistDeleteByArtistTrack(ctx context.Context, arg TrackArtistDeleteByArtistTrackParams) error {
	_, err := q.db.Exec(ctx, trackArtistDeleteByArtistTrack, arg.ArtistID, arg.TrackID)
	return err
}
