// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const trackCreate = `-- name: TrackCreate :one
INSERT INTO tracks (spotify_id, name, popularity)
VALUES ($1, $2, $3)
RETURNING id
`

type TrackCreateParams struct {
	SpotifyID  string
	Name       pgtype.Text
	Popularity pgtype.Int4
}

func (q *Queries) TrackCreate(ctx context.Context, arg TrackCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, trackCreate, arg.SpotifyID, arg.Name, arg.Popularity)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const trackGetAll = `-- name: TrackGetAll :many
SELECT id, spotify_id, name, popularity, updated_at
FROM tracks
`

func (q *Queries) TrackGetAll(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, trackGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.Popularity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackGetByPlaylist = `-- name: TrackGetByPlaylist :many
SELECT t.id, t.spotify_id, t.name, t.popularity, t.updated_at
FROM tracks t
LEFT JOIN playlist_tracks pt ON pt.track_id = t.id
WHERE pt.playlist_id = $1 AND pt.deleted_at IS NULL
`

func (q *Queries) TrackGetByPlaylist(ctx context.Context, playlistID int32) ([]Track, error) {
	rows, err := q.db.Query(ctx, trackGetByPlaylist, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.Popularity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackGetBySpotify = `-- name: TrackGetBySpotify :one
SELECT id, spotify_id, name, popularity, updated_at
FROM tracks
WHERE spotify_id = $1
`

func (q *Queries) TrackGetBySpotify(ctx context.Context, spotifyID string) (Track, error) {
	row := q.db.QueryRow(ctx, trackGetBySpotify, spotifyID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Name,
		&i.Popularity,
		&i.UpdatedAt,
	)
	return i, err
}

const trackUpdate = `-- name: TrackUpdate :exec
UPDATE tracks
SET
  name = coalesce($2, name),
  popularity = coalesce($3, popularity),
  updated_at = NOW()
WHERE id = $1
`

type TrackUpdateParams struct {
	ID         int32
	Name       pgtype.Text
	Popularity pgtype.Int4
}

func (q *Queries) TrackUpdate(ctx context.Context, arg TrackUpdateParams) error {
	_, err := q.db.Exec(ctx, trackUpdate, arg.ID, arg.Name, arg.Popularity)
	return err
}
