// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const trackCreate = `-- name: TrackCreate :one
INSERT INTO tracks (spotify_id, name, popularity)
VALUES ($1, $2, $3)
RETURNING id
`

type TrackCreateParams struct {
	SpotifyID  string
	Name       pgtype.Text
	Popularity pgtype.Int4
}

func (q *Queries) TrackCreate(ctx context.Context, arg TrackCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, trackCreate, arg.SpotifyID, arg.Name, arg.Popularity)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const trackGetAll = `-- name: TrackGetAll :many
SELECT id, spotify_id, name, popularity, updated_at
FROM tracks
`

func (q *Queries) TrackGetAll(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, trackGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.Popularity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackGetByName = `-- name: TrackGetByName :many
SELECT id, spotify_id, name, popularity, updated_at
FROM tracks
WHERE name = $1
`

func (q *Queries) TrackGetByName(ctx context.Context, name pgtype.Text) ([]Track, error) {
	rows, err := q.db.Query(ctx, trackGetByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.Popularity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackGetByPlaylist = `-- name: TrackGetByPlaylist :many
SELECT t.id, t.spotify_id, t.name, t.popularity, t.updated_at
FROM tracks t
LEFT JOIN playlist_tracks pt ON pt.track_id = t.id
WHERE pt.playlist_id = $1 AND pt.deleted_at IS NULL
`

func (q *Queries) TrackGetByPlaylist(ctx context.Context, playlistID int32) ([]Track, error) {
	rows, err := q.db.Query(ctx, trackGetByPlaylist, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.Popularity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackGetBySpotify = `-- name: TrackGetBySpotify :one
SELECT id, spotify_id, name, popularity, updated_at
FROM tracks
WHERE spotify_id = $1
`

func (q *Queries) TrackGetBySpotify(ctx context.Context, spotifyID string) (Track, error) {
	row := q.db.QueryRow(ctx, trackGetBySpotify, spotifyID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Name,
		&i.Popularity,
		&i.UpdatedAt,
	)
	return i, err
}

const trackGetCreatedFilteredPopulated = `-- name: TrackGetCreatedFilteredPopulated :many
SELECT t.id, t.spotify_id, t.name, t.popularity, t.updated_at, pt.id, pt.playlist_id, pt.track_id, pt.deleted_at, pt.created_at, p.id, p.spotify_id, p.name, p.description, p.public, p.track_amount, p.collaborative, p.cover_id, p.cover_url, p.owner_id, p.updated_at, p.snapshot_id, u.id, u.uid, u.name, u.display_name, u.email
FROM tracks t
LEFT JOIN playlist_tracks pt ON pt.track_id = t.id
LEFT JOIN playlist_users pu ON pu.playlist_id = pt.playlist_id
LEFT JOIN playlists p ON p.id = pu.playlist_id
LEFT JOIN users u ON p.owner_id = u.id
WHERE 
  pu.user_id = $3::int AND 
  pt.deleted_at IS NULL AND
  (p.id = $4::int OR NOT $5)
ORDER BY pt.created_at DESC
LIMIT $1 OFFSET $2
`

type TrackGetCreatedFilteredPopulatedParams struct {
	Limit            int32
	Offset           int32
	Column3          int32
	Column4          int32
	FilterPlaylistID interface{}
}

type TrackGetCreatedFilteredPopulatedRow struct {
	Track         Track
	PlaylistTrack PlaylistTrack
	Playlist      Playlist
	User          User
}

func (q *Queries) TrackGetCreatedFilteredPopulated(ctx context.Context, arg TrackGetCreatedFilteredPopulatedParams) ([]TrackGetCreatedFilteredPopulatedRow, error) {
	rows, err := q.db.Query(ctx, trackGetCreatedFilteredPopulated,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
		arg.FilterPlaylistID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackGetCreatedFilteredPopulatedRow
	for rows.Next() {
		var i TrackGetCreatedFilteredPopulatedRow
		if err := rows.Scan(
			&i.Track.ID,
			&i.Track.SpotifyID,
			&i.Track.Name,
			&i.Track.Popularity,
			&i.Track.UpdatedAt,
			&i.PlaylistTrack.ID,
			&i.PlaylistTrack.PlaylistID,
			&i.PlaylistTrack.TrackID,
			&i.PlaylistTrack.DeletedAt,
			&i.PlaylistTrack.CreatedAt,
			&i.Playlist.ID,
			&i.Playlist.SpotifyID,
			&i.Playlist.Name,
			&i.Playlist.Description,
			&i.Playlist.Public,
			&i.Playlist.TrackAmount,
			&i.Playlist.Collaborative,
			&i.Playlist.CoverID,
			&i.Playlist.CoverUrl,
			&i.Playlist.OwnerID,
			&i.Playlist.UpdatedAt,
			&i.Playlist.SnapshotID,
			&i.User.ID,
			&i.User.Uid,
			&i.User.Name,
			&i.User.DisplayName,
			&i.User.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackGetDeletedFilteredPopulated = `-- name: TrackGetDeletedFilteredPopulated :many
SELECT t.id, t.spotify_id, t.name, t.popularity, t.updated_at, pt.id, pt.playlist_id, pt.track_id, pt.deleted_at, pt.created_at, p.id, p.spotify_id, p.name, p.description, p.public, p.track_amount, p.collaborative, p.cover_id, p.cover_url, p.owner_id, p.updated_at, p.snapshot_id, u.id, u.uid, u.name, u.display_name, u.email
FROM tracks t
LEFT JOIN playlist_tracks pt ON pt.track_id = t.id
LEFT JOIN playlist_users pu ON pu.playlist_id = pt.playlist_id
LEFT JOIN playlists p ON p.id = pu.playlist_id
LEFT JOIN users u ON p.owner_id = u.id
WHERE
  pu.user_id = $3::int AND 
  pt.deleted_at IS NOT NULL AND
  (p.id = $4::int OR NOT $5)
ORDER BY pt.deleted_at DESC
LIMIT $1 OFFSET $2
`

type TrackGetDeletedFilteredPopulatedParams struct {
	Limit            int32
	Offset           int32
	Column3          int32
	Column4          int32
	FilterPlaylistID interface{}
}

type TrackGetDeletedFilteredPopulatedRow struct {
	Track         Track
	PlaylistTrack PlaylistTrack
	Playlist      Playlist
	User          User
}

func (q *Queries) TrackGetDeletedFilteredPopulated(ctx context.Context, arg TrackGetDeletedFilteredPopulatedParams) ([]TrackGetDeletedFilteredPopulatedRow, error) {
	rows, err := q.db.Query(ctx, trackGetDeletedFilteredPopulated,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
		arg.FilterPlaylistID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackGetDeletedFilteredPopulatedRow
	for rows.Next() {
		var i TrackGetDeletedFilteredPopulatedRow
		if err := rows.Scan(
			&i.Track.ID,
			&i.Track.SpotifyID,
			&i.Track.Name,
			&i.Track.Popularity,
			&i.Track.UpdatedAt,
			&i.PlaylistTrack.ID,
			&i.PlaylistTrack.PlaylistID,
			&i.PlaylistTrack.TrackID,
			&i.PlaylistTrack.DeletedAt,
			&i.PlaylistTrack.CreatedAt,
			&i.Playlist.ID,
			&i.Playlist.SpotifyID,
			&i.Playlist.Name,
			&i.Playlist.Description,
			&i.Playlist.Public,
			&i.Playlist.TrackAmount,
			&i.Playlist.Collaborative,
			&i.Playlist.CoverID,
			&i.Playlist.CoverUrl,
			&i.Playlist.OwnerID,
			&i.Playlist.UpdatedAt,
			&i.Playlist.SnapshotID,
			&i.User.ID,
			&i.User.Uid,
			&i.User.Name,
			&i.User.DisplayName,
			&i.User.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackUpdate = `-- name: TrackUpdate :exec
UPDATE tracks
SET
  name = coalesce($2, name),
  popularity = coalesce($3, popularity),
  updated_at = NOW()
WHERE id = $1
`

type TrackUpdateParams struct {
	ID         int32
	Name       pgtype.Text
	Popularity pgtype.Int4
}

func (q *Queries) TrackUpdate(ctx context.Context, arg TrackUpdateParams) error {
	_, err := q.db.Exec(ctx, trackUpdate, arg.ID, arg.Name, arg.Popularity)
	return err
}
